# Generated by Django 2.2 on 2019-04-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190429_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platter',
            name='dinner_platter',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='pasta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza_topping',
            name='pizza_topping',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza_topping_number',
            name='pizza_topping_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza_type',
            name='pizza_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salad',
            name='salad',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_extra',
            name='sub_extra',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
