# Generated by Django 2.2 on 2019-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190429_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField()),
                ('delivered', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='pasta',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='salad',
            new_name='item',
        ),
    ]
