# Generated by Django 2.2 on 2019-05-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190502_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
