# Generated by Django 2.2 on 2019-05-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190503_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
